### PR TITLE
Unlimited stock, Optimization and added extend hooks

### PR DESCRIPTION
**Pull request by ghost**
**Unlimited stock checkbox**
 - Moved 'Unlimited stock' out into checkbox on the Product / ProductVariation
 - Default ProductWarehouseStock Quantity change to 0
 - ProductWarehouseStock Quantity DB-field changed from Varchar to Int

**Extend reserved stock**
 - Changed hasAvailableStock function to call the new function getReservedStock

**Possible to prevent onPlacement stock decrement**
 - Added variable $preventDecrement that specifies if stock should be decrmented on placement
 - Added extend point, 'onBeforeDecrementStock', where $preventDecrement can be set to true
 - Added extend point, 'onAfterDecrementStock', to handle any actions after stock decrement

**Reserved stock count optimization**
 - Optimized function to get reserved stock count in the store.
 - Added extend point, 'updateOrderStatusArray' to allow for more statuses to be checked

### CODE REVIEW

**Comment by bummzack** [comment]
Looks good to me. I'll leave it up to @wilr to review/merge.

**Comment by wilr** [comment]
@lundco Looks good! though it will break quietly for anyone upgrading. Before this is merged I'd be keen to see a DB query to bulk migrate `-1` values to the checkbox. Perhaps on the `requireDefaultRecords` on the extension so that it's done automatically on dev/build for people otherwise I can see it tripping people up!

**Comment by lundco** [comment]
@wilr I've made an DB query on the `requireDefaultRecords` where it finds all stock with -1, changes it to 0 and update product to have unlimited stock.

**Comment by lundco** [comment]
@wilr Additional commit on it's way to fix an issue we came across.

**Comment by CMeldgaard** [comment]
@wilr  that should be the last commit

**Pull request merged**
